apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  MONGO_URI: "mongodb+srv://dbuser:dbUserPassword@flask.zvkal.mongodb.net/?retryWrites=true&w=majority&appName=flask"
  BACKEND_PORT: "5000"
  FLASK_ENV: "development"
