apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: proxy
data:
  nginx.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://frontend-service.frontend.svc.cluster.local:8080;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Host $host;
        }

        location /submit {
            proxy_pass http://backend-service.backend.svc.cluster.local:5000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Host $host;
        }
    }
