apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: anshaantony22/frontend-image:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: frontend-config  # Reference the ConfigMap for environment variables
